### ISSUE TITLE
IE7, IE8 compatibility

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/lodash-deep#18]
Currently lodash-deep is not compatible with IE7 and IE8. The incomatibility issues should be identified and resolved.

**Comment by pribilinskiy** [comment]
`_.deepSet` malfunctioning in IE8
![image](https://cloud.githubusercontent.com/assets/3078595/6348333/40f34990-bc27-11e4-9f7b-9ae4b7e96133.png)

* when the object doesn't exist, an array is created
* when the object exist, the value appears under key with an empty string identifier

**Comment by marklagendijk** [comment]
If somebody wants to pick this up, I will accept pull requests.
