### ISSUE TITLE
deepPluck returns non-empty array ([0]) when there are zero matches

### ISSUE THREAD

**Issue by bkinnaird** [marklagendijk/lodash-deep#33]
The following line 

`_.deepPluck([],"fakepath.fakepath") `

is returning a non-empty array with a "zero" in the first position.  My expectation was that it would return an empty array.

**Comment by marklagendijk** [comment]
I tested this in Node and different browsers, and it works as expected. I think you where misled by the way (Chrome) developers tools sometimes display an empty array.
