### ISSUE TITLE
Release 1.5.3 doesn't include deepDefault

### ISSUE THREAD

**Issue by IjinPL** [marklagendijk/lodash-deep#40]

**Comment by robertklep** [comment]
Just noticed this myself.

**Comment by IjinPL** [comment]
When can I expect update?

**Comment by marklagendijk** [comment]
Sorry about this. I created a canary branch to prevent issues like this, but then forgot to use it. I just released 1.6.0.

**Comment by robertklep** [comment]
Thanks Mark :+1:
