### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by user453584** [marklagendijk/lodash-deep#41]
@marklagendijk This probably isn't the right place to do this, so apologies in advance for muddying up the issue tracker, but I had been looking for a library like this one and was half way through writing my own when I discovered yours.

I've been perusing the source code and find it both readable and very well-written. Thank you for your work creating this wonderful complement to lodash!

**Comment by marklagendijk** [comment]
@user453584 thanks for the compliment! I highly care about the cleanliness and quality of code and am glad that it shows :). If you also care about that you should really read [Clean Code](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882), if you didn't already.
