### ISSUE TITLE
Consider deprecating this module

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/lodash-deep#47]
The latest version of Lodash now supports using paths instead of just keys. I think most of the functionality of this module is now covered by Lodash itself:

- [_.get](https://lodash.com/docs#get)
- [_.set](https://lodash.com/docs#set)
- [_.has](https://lodash.com/docs#has)
- [_.result](https://lodash.com/docs#result)
- [_.invoke](https://lodash.com/docs#invoke)
- [_.pluck](https://lodash.com/docs#pluck)
- [_.matchesProperty](https://lodash.com/docs#matchesProperty)
- [_.method](https://lodash.com/docs#method)
- [_.property](https://lodash.com/docs#property)

**Comment by marklagendijk** [comment]
@jdalton does Lodash now cover all the functionality lodash-deep? Should I just deprecate lodash-deep?

**Comment by mik01aj** [comment]
Not all of it. There is nothing for iteration over nested tree structures (so that the callback gets each path).

**Comment by jdalton** [comment]
What @mik01aj said ; )

**Comment by marklagendijk** [comment]
Ok. When I get some time I should give this module a good look again, and create a 2.0 version which removes everything which Lodash now supports natively.

**Comment by pribilinskiy** [comment]
+1

**Comment by marklagendijk** [comment]
I created a very much trimmed down 2.0 version.

**Comment by jdalton** [comment]
:clap: Congrats on 2.0!

**Comment by marklagendijk** [comment]
@jdalton thanks! I think this will help people to discover the awesome new features which Lodash now supports natively.
It will also help with clarifying which 'deepSomething' methods people are still missing currently, so that they hopefully end up in Lodash itself, eventually.
