### ISSUE TITLE
_.deepSet(...) does not have the exact same behavior as _.set(...)

### ISSUE THREAD

**Issue by austenLacy** [marklagendijk/lodash-deep#50]
There is slight difference between lodash-deep `_.deepSet(...)` and lodash `_.set(...)`. 

With lodash `_.set` if an object property that you wish to set in the future is a string or number and then try to set it with an assumption that it is an object with properties it will silently err and not actually set the value. `_.deepSet` however will ignore the type of the originally initialized value and will set it with whatever you set (i.e. change the original value to an object with its associated properties).

Example:

```javascript

/*
    _.set(...) === _.deepSet(...) if setting same type (i.e. Number -> Number)
*/
var obj = { 'a': [{ 'b': { 'c': 3 } }] };
console.log(obj.a[0].b.c) // prints out 3

// _.set(...) === _.deepSet(...) 
// in this case
_.set(obj, 'a[0].b.c', 4000); 
console.log(obj.a[0].b.c) // prints out 4000


/*
   _.set(...) !== _.deepSet(...) if setting different type (i.e. String -> Object)
*/
var obj = { 'a': [{ 'b': { 'c': '' } }] };
console.log(obj.a[0].b.c) // prints out empty string

// _.set(...) !== _.deepSet(...)
// in this case
// here we are treating 'c' as an object with a property
_.set(obj, _.set(obj, 'a[0].b.c.someProp', 4000); 
console.log(obj.a[0].b.c) // still prints out empty string

// however _.deepSet(...) will set fine
_.deepSet(obj, _.set(obj, 'a[0].b.c.someProp', 4000); 
console.log(obj.a[0].b.c) // prints out an Object { someProp: 4000 }
```

This isn't so much a bug, as much as an instance where the two are not exactly the same so it might be worth noting in the documentation somewhere. I'm open to creating a PR to modify the docs or if the main contribs for lodash-deep wish to increase parity between the two then I don't mind creating a PR for that as well.

![screen shot 2015-12-14 at 2 00 56 pm](https://cloud.githubusercontent.com/assets/8395995/11790714/3790fa84-a26b-11e5-9254-a90563fedead.png)

**Comment by marklagendijk** [comment]
I think it would be best to create a 2.0 version of lodash-deep, from which all methods which are covered by Lodash itself are removed (which is nearly everything).

**Comment by austenLacy** [comment]
I'm all for that solution
